package mobile.Pages;

import io.appium.java_client.android.AndroidDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;

public class CreateCommunity extends Pages{

    /**
     *
     */
    @FindBy(xpath="//android.view.View[@content-desc='Create a community'")
    WebElement CreateCommunityPageName;


    /**
     *
     */
    @FindBy(xpath="(//android.widget.EditText)[1]")
    WebElement CreateCommunityNameTextBox;


    /**
     *
     */
    @FindBy(xpath="(//android.view.View)[11]")
    WebElement CreateCommunityNSFWButton;


    /**
     *
     */
    @FindBy(xpath="//android.view.View[@content-desc='Community type']")
    WebElement CreateCommunityTypeWindow;


    /**
     * this is the community type
     */
    @FindBy(xpath = "(//android.widget.Button)[3]")
    WebElement communityType;

    /**
     *
     */
    @FindBy(xpath="(//android.view.View)[8]")
    WebElement CreateCommunityTypePublic;


    /**
     *
     */
    @FindBy(xpath="(//android.view.View)[9]")
    WebElement CreateCommunityTypeRestricted;

    /**
     *
     */
    @FindBy(xpath="(//android.view.View)[10]")
    WebElement CreateCommunityTypePrivate;

    @FindBy(xpath = "//android.widget.Button[@content-desc=\"Create Community\"]\n")
    WebElement CreateCommunityButton;

    /**
     * this is the community created
     */
    @FindBy(xpath = "(//android.view.View)[14]")
    WebElement communityTitleText;

    /**
     * this is the constructor of the class and it initializes all of its members using PageFactory class
     *
     * @param driver : which is generated by selenium testcase
     */
    public CreateCommunity(AndroidDriver driver) {
        super(driver);
    }

    public boolean createComm(String Comm,String Type,String NSFW) {

        CreateCommunityNameTextBox.click();
        threadSleep(1);
        CreateCommunityNameTextBox.sendKeys(Comm);
        driver.hideKeyboard();

        communityType.click();
        threadSleep(1);

        if(Type.equalsIgnoreCase("private")) {
            CreateCommunityTypePrivate.click();
        }else if(Type.equalsIgnoreCase("public")){
            CreateCommunityTypePublic.click();
        }else {
            CreateCommunityTypeRestricted.click();
        }
        threadSleep(1);
        if(NSFW.equalsIgnoreCase("+18")){
            CreateCommunityNSFWButton.click();
        }

        if(CreateCommunityButton.isEnabled()){
            CreateCommunityButton.click();
        }
        else{
            return false;
        }

        return communityTitleText.getAttribute("content-desc").contains(Comm);


    }

    public boolean makeItPrivate(){
        try{
            CreateCommunityTypeWindow.click();
            CreateCommunityTypePrivate.click();
        }catch(Exception i){
             return false;
        }
        return true;
    }
}
