package mobile.Pages;

import io.appium.java_client.android.AndroidDriver;

public class EditScreenPage extends Pages {

    /**
     * this is the constructor of the class and it initializes all of its members using PageFactory class
     *
     * @param driver : which is generated by selenium testcase
     */
    public EditScreenPage(AndroidDriver driver) {
        super(driver);
    }
}
