package mobile.Pages;

import io.appium.java_client.android.AndroidDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;

public class SearchPage extends Pages{
    @FindBy(id = "SearchBar")
    WebElement SearchBar;

    @FindBy(id="FirstCommunity")
    WebElement FirstCommunity;

    /**
     * this is the constructor of the class and it initializes all of its members using PageFactory class
     *
     * @param driver : which is generated by selenium testcase
     */
    public SearchPage(AndroidDriver driver) {
        super(driver);
    }

    public boolean searchForCommunity(String CommunityName) {

        SearchBar.sendKeys(CommunityName);
        SearchBar.sendKeys("Enter");

        if(  FirstCommunity.isDisplayed())
        {
            FirstCommunity.click();
            return true;
        }
    return false;
    }



}
