package mobile.Pages;

import io.appium.java_client.android.AndroidDriver;
import org.openqa.selenium.By;

public class SettingPage extends Pages{
    /**
     * this is the constructor of the class and it initializes all of its members using PageFactory class
     *
     * @param driver : which is generated by selenium testcase
     */
    public SettingPage(AndroidDriver driver) {
        super(driver);
    }

    public void gotoSettings(){
        threadSleep(2);
        driver.findElement(By.xpath("(//android.widget.Button)[4]")).click();
        threadSleep(1);
        scrollToEndAction();
        threadSleep(1);
        driver.findElement(By.xpath("(//android.view.View)[16]")).click();
    }


}
