package mobile.Pages;

import io.appium.java_client.android.AndroidDriver;
import org.openqa.selenium.By;

public class SettingPage extends Pages{
    /**
     * this is the constructor of the class and it initializes all of its members using PageFactory class
     *
     * @param driver : which is generated by selenium testcase
     */
    public SettingPage(AndroidDriver driver) {
        super(driver);
    }

    public void gotoSettings(){
        threadSleep(8);
        driver.findElement(By.xpath("(//android.widget.Button)[4]")).click();
        threadSleep(5);
        scrollToEndAction();
        threadSleep(3);
        driver.findElement(By.xpath("(//android.view.View)[16]")).click();
    }
    public void changePassword(String OldPass,String NewPass){
        threadSleep(2);
        driver.findElement(By.xpath("(//android.view.View)[9]")).click();
        threadSleep(3);
        driver.findElement(By.xpath("(//android.view.View)[10]")).click();
        threadSleep(5);
        driver.findElement(By.xpath("(//android.widget.EditText)[1]")).click();
        driver.findElement(By.xpath("(//android.widget.EditText)[1]")).sendKeys(OldPass);
        threadSleep(1);
        driver.findElement(By.xpath("(//android.widget.EditText)[2]")).click();
        driver.findElement(By.xpath("(//android.widget.EditText)[2]")).sendKeys(NewPass);
        threadSleep(1);
        driver.findElement(By.xpath("(//android.widget.EditText)[3]")).click();
        driver.findElement(By.xpath("(//android.widget.EditText)[3]")).sendKeys(NewPass);
        threadSleep(3);
        driver.findElement(By.xpath("(//android.widget.Button)[7]")).click();
        threadSleep(2);
        driver.findElement(By.xpath("(//android.widget.EditText)[1]")).click();
        threadSleep(3);
        driver.findElement(By.xpath("(//android.widget.EditText)[1]")).click();
        threadSleep(2);
        driver.findElement(By.xpath("(//android.widget.EditText)[1]")).click();
        threadSleep(5);
        driver.findElement(By.xpath("(//android.widget.EditText)[15]")).click();
        threadSleep(4);
    }

    public void changeCounty(){
        threadSleep(2);
        driver.findElement(By.xpath("(//android.view.View)[9]")).click();
        threadSleep(3);
        driver.findElement(By.xpath("(//android.view.View)[11]")).click();
        threadSleep(5);
        driver.findElement(By.xpath("(//android.view.View)[10]")).click();
        threadSleep(5);
    }

    public void changeGender(){
        threadSleep(3);
        driver.findElement(By.xpath("(//android.view.View)[9]")).click();
        threadSleep(3);
        driver.findElement(By.xpath("(//android.view.View)[12]")).click();
        threadSleep(5);
        driver.findElement(By.xpath("(//android.view.View)[7]")).click();
        threadSleep(5);
    }

    public void unblock(){
        threadSleep(3);
        driver.findElement(By.xpath("(//android.view.View)[9]")).click();
        threadSleep(3);
        driver.findElement(By.xpath("(//android.view.View)[14]")).click();
        threadSleep(5);
        driver.findElement(By.xpath("(//android.widget.Button)[2]")).click();
        threadSleep(5);
    }

    public void allowFollow(){
        threadSleep(3);
        driver.findElement(By.xpath("(//android.view.View)[9]")).click();
        threadSleep(3);
        driver.findElement(By.xpath("//android.widget.Switch")).click();
        threadSleep(5);

    }


}
