package constants;

/**
 * this is the class which contains constant data related to tests
 */
public class TestConstants {

    /**
     * this is the url of home page of reddit
     */
    public static final String HOME_URL = "https://www.reddit.com/";

    /**
     * constant which represents the path of reports to generated into
     */
    public static final String REPORT_PATH = System.getProperty("user.dir")+ "\\reports\\generalReport.html";

    /**
     * this is the document title generated by the extent report
     */
    public static final String DOCUMENT_TITLE = "Test Results";

    /**
     * This is the report name
     */
    public static final String REPORT_NAME = "Web Automation Results";

    /**
     * this is the path of the file which contains the general properties of the project like browser name, etc...
     */
    public static final String PROP_PATH = System.getProperty("user.dir")+ "\\src\\test\\java\\resources\\GlobalData.properties";


    /**
     * this is constants to define the used browser and check which one to use to automate the tests
     */
    public static final String BROWSER = "browser";

    /**
     * using this to run the tests on the chrome
     */
    public static final String BROWSER_CHROME = "chrome";

    /**
     * using this to run the tests on firefox
     */
    public static final String BROWSER_FIREFOX = "firefox";

    /**
     * using this to run the tests on microsoft edge
     */
    public static final String BROWSER_MSEDGE = "edge";

    /**
     * this is the place where screenshots will be taken
     */
    // System.getProperty("user.dir") +
    public static final String SCREENSHOT_PATH ="screenshots/";

    /**
     * this is the place where recorded videos will be stored
     */
    public static final String RECORDED_VIDEOS_PATH = System.getProperty("user.dir") + "\\reports\\RecordedVideos\\";

    /**
     * this is the place where the excel file that contains data for tests to execute are extracted from
     */
    public static final String EXCEL_PATH = System.getProperty("user.dir") + "\\src\\test\\java\\resources\\data.xlsx";

    /**
     * this is the implicit Timeout in seconds to wait on an element implicitly before terminating the test
     */
    public static final int IMPLICIT_TIMEOUT_SECONDS = 2;

    /**
     * this is the standard explicit Timeout in seconds to wait explicitly on web element
     */
    public static final int EXPLICIT_TIMEOUT_SECONDS = 3;

    /**
     * this is the sheetName that contains login data
     */
    public static final String LOGIN_TEST_DATA = "loginTestData";


    /**
     * this is tag name that defines username which is related to excel data
     */
    public static final String USERNAME_TAG_EXCEL = "username";

    /**
     * this is tag name that defines password which is related to excel data
     */
    public static final String PASSWORD_TAG_EXCEL = "password";

    /**
     * this is tag name that defines expectedResult from signing in which is related to excel data
     */
    public static final String EXPECTED_RES_TAG_EXCEL = "expectedResult";

}
