package web.pageObjects;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import web.AbstractComponents.AbstractComponent;

public class CommunityPage extends AbstractComponent {

    /**
     * this the driver that's used to to automate the tests
     */
    WebDriver driver;

    /**
     * this is the community name in the page
     */
    @FindBy(tagName = "h1")
    WebElement communityNameLabel;

    /**
     * this is the constructor of the class and it initializes all of its members using PageFactory class
     *
     * @param driver : which is generated by selenium testcase
     */
    public CommunityPage(WebDriver driver) {
        super(driver);
        this.driver = driver;
    }

    /**
     * this method is used to get the name of the current community page
     */
    public String getCommunityName(){
        return communityNameLabel.getText();
    }
}
