package web.pageObjects;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import web.AbstractComponents.AbstractComponent;

public class web_Profile extends AbstractComponent {

    @FindBy(xpath = "//*[@id=\"root\"]/div[2]/div/div[2]/div[1]/div/span[2]")
    WebElement Name;

    @FindBy(xpath = "//*[@id=\"root\"]/div[2]/div/div[2]/div[1]/div[2]/div[2]/div[3]/div/span")
    WebElement Followers;

    @FindBy(xpath = "")
    WebElement SearchFollower;

    @FindBy(xpath = "")
    WebElement SearchResultFollower;

    @FindBy(xpath = "//button[text()='overview']")
    WebElement OverViewButton;

    @FindBy(xpath = "/html/body/div[1]/div[1]/header/div/button[3]")
    WebElement CommentsButton;

    @FindBy(xpath = "/html/body/div[1]/div[1]/header/div/button[2]")
    WebElement PostsButton;

    @FindBy(xpath = "/html/body/div[1]/div[1]/header/div/button[4]")
    WebElement HistoryButton;

    @FindBy(xpath = "/html/body/div[1]/div[1]/header/div/button[5]")
    WebElement SavedButton;

    @FindBy(xpath = "/html/body/div[1]/div[1]/header/div/button[8]")
    WebElement DownVotedButton;

    @FindBy(xpath = "/html/body/div[1]/div[1]/header/div/button[6]")
    WebElement HiddenButton;

    @FindBy(xpath = "/html/body/div[1]/div[1]/header/div/button[7]")
    WebElement UpVotedButton;

    @FindBy(xpath = "/html/body/div[1]/div[2]/div/div[2]/div[1]/div[2]/div[1]/a/svg/path")
    WebElement SettingsButton;

    /**
     * this is the title of the first post appears in my profile
     */

    @FindBy(xpath = "//*[@id=\"root\"]/div[2]/div/div[1]/div[3]/div[2]/div/div[2]/h6")
    WebElement FirstPostTitle;

    /**
     * This is the Body of the First Post appears in my profile
     */

    @FindBy(xpath = "//*[@id=\"root\"]/div[2]/div/div[1]/div[3]/div[2]/div/div[3]")
    WebElement FirstPostBodyText;

    /**
     * This is the Name  of the community First Post appears in my profile
     */


    @FindBy(xpath = "/html/body/div[1]/div[2]/div/div[1]/div[3]/div[2]/div/div[1]/div/a[1]/span")
    WebElement FirstPostCommunity;





    /**
     * this is the constructor of the class and it initializes all of its members using PageFactory class
     *
     * @param driver : which is generated by selenium testcase
     */
    public web_Profile(WebDriver driver) {
        super(driver);
    }


    public boolean checkPostText(String Title,String Body,String Community){
        threadSleep(5);
        waitForWebElementToAppear(FirstPostCommunity,5);


        if(Title.equals(FirstPostTitle.getText())&&Body.equals(FirstPostBodyText.getText())&&Community.equals(FirstPostCommunity.getText()) ){
            FirstPostCommunity.click();
            return true;
        }
        return false;
    }

    public boolean checkName(String LoggedInName) {
        //waitForWebElementToAppear(Name,1);
        threadSleep(2);
        return Name.getText() .equals(LoggedInName);
    }

    public String getFollowers() {
        ///to int in java
        waitForWebElementToAppear(Followers,1);
        return Followers.getText();
    }

    public boolean checkFollowers(String FollowerName) {
        Followers.click();
        SearchFollower.sendKeys(FollowerName);
        if (SearchResultFollower.isDisplayed()) {
            if (SearchResultFollower.getText() == FollowerName) {
                SearchResultFollower.click();
                return checkName(FollowerName);
            } else {
                return false;
            }
        } else {
            return false;
        }
    }

    public boolean checkCommentsButton() {

        waitForWebElementToAppear(DownVotedButton,1);
        if (CommentsButton.isDisplayed()) {
            CommentsButton.click();
            threadSleep(1);
            if (driver.findElement(By.xpath("/html/body/div[1]/div[2]/div/div[1]/div[5]/p")).getText().equals( "hmm... u/lawfulenvelope hasn't commented on anything")&&
                    CommentsButton.getCssValue("color").equals("rgba(0, 121, 211, 1)")) {
                return true;
            } else {
                return false;
            }
        } else {
            return false;
        }
    }

    public boolean checkHistoryButton() {
        waitForWebElementToAppear(HistoryButton,1);
        if (HistoryButton.isDisplayed()) {
            HistoryButton.click();
            threadSleep(1);
            if (driver.findElement(By.xpath("//*[@id=\"root\"]/div[2]/div/div[1]/div[4]/p")).getText().equals( "hmm... looks like you haven't recently viewed anything yet")&&
                    HistoryButton.getCssValue("color").equals("rgba(0, 121, 211, 1)")) {
                return true;
            } else {
                return false;
            }
        } else {
            return false;
        }
    }

    public boolean checkPostsButton() {
        waitForWebElementToAppear(PostsButton,1);
        if (PostsButton.isDisplayed()) {
            PostsButton.click();
            threadSleep(1);

            if (driver.findElement(By.xpath("/html/body/div[1]/div[2]/div/div[1]/div[5]/p")).getText().equals( "hmm... u/lawfulenvelope hasn't posted recently")&&
                    PostsButton.getCssValue("color").equals("rgba(0, 121, 211, 1)")) {
                return true;
            } else {
                return false;
            }
        } else {
            return false;
        }
    }

    public boolean checkSavedButton() {
        waitForWebElementToAppear(SavedButton,1);
        if (SavedButton.isDisplayed()) {
            SavedButton.click();
            threadSleep(1);
            System.out.println(SavedButton.getCssValue("color"));
            threadSleep(1);

            if (driver.findElement(By.xpath("/html/body/div[1]/div[2]/div/div[1]/div[4]/p")).getText().equals( "hmm... looks like you haven't saved anything yet")&&
                    SavedButton.getCssValue("color").equals("rgba(0, 121, 211, 1)")) {
                return true;
            } else {
                return false;
            }
        } else {
            return false;
        }
    }

    public boolean checkHiddenButton() {
        waitForWebElementToAppear(HiddenButton,1);
        if (HiddenButton.isDisplayed()) {
            HiddenButton.click();
            threadSleep(1);
            if (driver.findElement(By.xpath("/html/body/div[1]/div[2]/div/div[1]/div[4]/p")).getText().equals( "hmm... looks like you haven't Hidden anything yet")&&
                    HiddenButton.getCssValue("color").equals("rgba(0, 121, 211, 1)")) {
                return true;
            } else {
                return false;
            }
        } else {
            return false;
        }
    }

    public boolean checkUpVotedButton() {
        waitForWebElementToAppear(UpVotedButton,1);
        if (UpVotedButton.isDisplayed()) {
            UpVotedButton.click();
            threadSleep(1);
            if (driver.findElement(By.xpath("/html/body/div[1]/div[2]/div/div[1]/div[4]/p")).getText().equals( "hmm... looks like you haven't upvoted anything yet")&&
                    UpVotedButton.getCssValue("color").equals("rgba(0, 121, 211, 1)")) {

                return true;
            } else {
                return false;
            }
        } else {
            return false;
        }
    }



    public boolean checkDownVotedButton() {
        waitForWebElementToAppear(DownVotedButton,1);
        if (DownVotedButton.isDisplayed()) {
            DownVotedButton.click();
            threadSleep(1);
            if (driver.findElement(By.xpath("/html/body/div[1]/div[2]/div/div[1]/div[4]/p")).getText().equals( "hmm... looks like you haven't downvoted anything yet")&&
                    DownVotedButton.getCssValue("color").equals("rgba(0, 121, 211, 1)")) {
                return true;
            } else {
                return false;
            }
        } else {
            return false;
        }
    }

    public boolean checkOverViewButton() {
        waitForWebElementToAppear(OverViewButton,1);
        if (OverViewButton.isDisplayed()) {
            OverViewButton.click();
            threadSleep(1);
            if (driver.findElement(By.xpath("/html/body/div[1]/div[2]/div/div[1]/div[5]/p")).getText().equals( "hmm... u/lawfulenvelope hasn't posted recently")&&
            OverViewButton.getCssValue("color").equals("rgba(0, 121, 211, 1)")) {
                return true;
            } else {
                return false;
            }
        } else {
            return false;

        }

    }

    public void gotoSettings(){
        waitForWebElementToAppear(SettingsButton,1);
        if(SettingsButton.isDisplayed()){
            SettingsButton.click();
            threadSleep(1);
        }
    }

    public void addSocialLink(String Url){

    }


    /**
     * this function to navigate you from Profile to the community of the first post appears in your profile
     */
   public void gotoFirstPostCommunity(){
       threadSleep(2);
        waitForWebElementToAppear(FirstPostCommunity,5);
        FirstPostCommunity.click();
   }

    /**
     * This Function navigate to a NSFW Community
     */

   public void gotoNFSW(){
       threadSleep(1);
       driver.findElement(By.xpath("/html/body/div[1]/div/div/button[2]")).click();
   }

   public boolean checkForSpoiler(){
       //make sure that you just posted spoiler poster
       threadSleep(2);
       if(driver.findElement(By.xpath("//*[@id=\"root\"]/div[2]/div/div[1]/div[3]/div[2]/div/div[2]/span")).getText().equals("spoiler")){
           driver.findElement(By.xpath("/html/body/div[1]/div[2]/div/div[1]/div[3]/div[2]/div/div[2]")).click();

           if(driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div[1]/div[1]/div[2]/div[1]/div/div[2]/div/div[3]")).getCssValue("filter").equals("blur(3px)")){
               return true;
           }
           return true;
       }
       return false;
   }

    public boolean checkForNSFW(){
        //make sure that you just posted spoiler poster
        threadSleep(2);
        if(driver.findElements(By.xpath("//*[@id=\"root\"]/div[2]/div/div[1]/div[3]/div[2]/div/div[2]/span")).size() == 0){
            return false;
        }
        else if(driver.findElement(By.xpath("//*[@id=\"root\"]/div[2]/div/div[1]/div[3]/div[2]/div/div[2]/span")).getText().equals("NSFW")){
            driver.findElement(By.xpath("/html/body/div[1]/div[2]/div/div[1]/div[3]/div[2]/div/div[2]")).click();

            if(driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div[1]/div[1]/div[2]/div[1]/div/div[2]/div/div[3]")).getCssValue("filter").equals("blur(3px)")){
                return true;
            }
            return true;
        }
        return false;
    }


   public boolean checkNameAbout(String Name,String About){
       threadSleep(4);

       if(driver.findElement(By.xpath("/html/body/div[1]/div[2]/div/div[2]/div[1]/div/span[1]")).getText().equals(Name)
       && driver.findElement(By.xpath("/html/body/div[1]/div[2]/div/div[2]/div[1]/div/p")).getText().equals(About)){
           return true;
       }
       return false;
   }

}
