package web.pageObjects;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import web.AbstractComponents.AbstractComponent;

public class web_CreatePost extends AbstractComponent {

    /**
     * this is the constructor of the class and it initializes all of its members using PageFactory class
     *
     * @param driver : which is generated by selenium testcase
     */
    public web_CreatePost(WebDriver driver) {
        super(driver);
    }

    @FindBy(xpath ="/html/body/div/div/div/div[1]/form/div[2]/div/div[1]/input")
    WebElement ChooseCommunity;

    @FindBy(xpath ="/html/body/div[1]/div/div/div[1]/form/div[2]/div/div[2]/ul[1]/li/div[2]/div")
    WebElement FirstCommunity;

    @FindBy(xpath ="/html/body/div[1]/div/div/div[1]/form/div[3]/div[2]/div[1]/textarea[1]")
    WebElement Title;

    @FindBy(xpath = "/html/body/div[1]/div/div/div[1]/form/div[3]/div[4]/div[1]/button[2]")
    WebElement PostButton;


    @FindBy(xpath = "/html/body/div[1]/div/div/div[1]/form/div[3]/div[2]/div[2]/div[1]/button[1]")
    WebElement BoldButton;

    @FindBy(xpath = "/html/body/div[1]/div/div/div[1]/form/div[3]/div[2]/div[2]/div[1]/button[2]")
    WebElement ItalicButton;

    @FindBy(xpath = "/html/body/div[1]/div/div/div[1]/form/div[3]/div[2]/div[2]/div[1]/button[4]")
    WebElement LineThroughButton;

    @FindBy(xpath = "/html/body/div[1]/div/div/div[1]/form/div[3]/div[2]/div[2]/div[1]/div[1]/div[5]/img")
    WebElement MonoSpaceButton;

    @FindBy(xpath = "//*[@id=\"root\"]/div/div/div[1]/form/div[3]/div[2]/div[2]/div[2]/div/div[1]")
    WebElement BodyText;

    @FindBy(xpath = "/html/body/div[1]/div/div/div[1]/form/div[3]/div[2]/div[2]/div[1]/button[6]")
    WebElement SubScript;

    @FindBy (xpath ="/html/body/div[1]/div/div/div[1]/form/div[3]/div[3]/button[1]" )
    WebElement SpoilerButton;
    @FindBy (xpath = "/html/body/div[1]/div/div/div[1]/form/div[3]/div[3]/button[2]")
    WebElement NSFWButton;

    public boolean typeBody(String body){
        if(body.equals("")){
            return true;
        }

        BodyText.click();
        SubScript.click();
        BoldButton.click();
        ItalicButton.click();
        LineThroughButton.click();
        SubScript.click();


        BodyText.sendKeys(body);

        threadSleep(2);


        WebElement Text=  driver.findElement(By.xpath("/html/body/div[1]/div/div/div[1]/form/div[3]/div[2]/div[2]/div[2]/div/div[1]"));
        if(Text.getText().equals(body)){
          return true;
        }
        return false;
    }


    public boolean CreatePost(String title,String Body,String Community){
        waitForWebElementToAppear(ChooseCommunity,5);
        ChooseCommunity.click();
        threadSleep(1);
        ChooseCommunity.sendKeys(Community);


        FirstCommunity.click();
        Title.sendKeys(title);

        threadSleep(2);
        if(!typeBody(Body)){
            return false;
        }



        if(PostButton.isEnabled()){
            PostButton.click();
            threadSleep(5);
            return true;

        }else{
            return false;
        }

    }

    /**
     * this function used to choose the post to be spoiler
     */
    public void spoilerPost(){
        waitForWebElementToAppear(SpoilerButton,5);
        SpoilerButton.click();
    }

    /**
     * this function used to choose the post to be NSFW
     */
    public void NSFWPost(){
        waitForWebElementToAppear(SpoilerButton,5);
        NSFWButton.click();
    }
}
