package web.pageObjects;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import web.AbstractComponents.AbstractComponent;

public class web_Community extends AbstractComponent {

    /**
     * this is the constructor of the class and it initializes all of its members using PageFactory class
     *
     * @param driver : which is generated by selenium testcase
     */
    public web_Community(WebDriver driver) {
        super(driver);
    }


    @FindBy(xpath = "/html/body/div/div[3]/div/div[1]/div[3]/div[2]/a/h3")
    WebElement FirstPostTitle;


    @FindBy(xpath = "/html/body/div/div[3]/div/div[1]/div[3]/div[2]/div[2]")
    WebElement FirstPostBodyText;


    @FindBy(xpath = "/html/body/div/div[3]/div/div[1]/div[3]/div[2]/div[2]   ")
    WebElement CommunityName;


    public boolean checkForCommunityName(String CommName){
        waitForWebElementToAppear(CommunityName,5);
        if(CommunityName.equals(CommName)){
            return true;
        }
        return false;
    }

    public boolean checkPostText(String Title,String Body,String Community){

        waitForWebElementToAppear(FirstPostTitle,4);

        if(Title.equals(FirstPostTitle.getText())&&Body.equals(FirstPostBodyText.getText())&&checkForCommunityName(Community)){
            return true;
        }
        return false;
    }
}
