package web.pageObjects;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import web.AbstractComponents.AbstractComponent;

public class web_Settings extends AbstractComponent {

    @FindBy(id = "settings")
    WebElement UserSettingsPage;


    /**
     * this is the constructor of the class and it initializes all of its members using PageFactory class
     *
     * @param driver : which is generated by selenium testcase
     */
    public web_Settings(WebDriver driver) {
        super(driver);
    }

    public boolean checkForSettingsPage() {
        waitForWebElementToAppear(UserSettingsPage, 1);

        if (UserSettingsPage.isDisplayed()) {
            return true;
        }else {
            return false;
        }
    }
}
