package web.pageObjects;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import web.AbstractComponents.AbstractComponent;

public class web_CreateCommunity extends AbstractComponent {
    /**
     * this is the constructor of the class and it initializes all of its members using PageFactory class
     *
     * @param driver : which is generated by selenium testcase
     */
    public web_CreateCommunity(WebDriver driver) {
        super(driver);
    }
    @FindBy(xpath = "/html/body/div[2]/div[3]/div/div[1]/p[2]")
    WebElement ErrorMessage;
    @FindBy(xpath = "/html/body/div[2]/div[3]/div/div[1]/div[3]/div/input")
    WebElement CommunityName;


    @FindBy(xpath = "/html/body/div[2]/div[3]/div/div[2]/a/button")
    WebElement CreateCommunityButton;

    public Boolean setCommunityName (String Name){
        waitForWebElementToAppear(CommunityName,5);
        CommunityName.click();
        CommunityName.sendKeys(Name);
        threadSleep(1);

        if(ErrorMessage.isDisplayed()){
            return false;
        }
        threadSleep(1);
        CreateCommunityButton.click();
        threadSleep(2);
        return true;
    }


}
