package web.pageObjects;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;

public class web_OtherUserProFile extends web_Profile {

    @FindBy(xpath = "")
    WebElement FollowButton;

    /**
     * this is the constructor of the class and it initializes all of its members using PageFactory class
     *
     * @param driver : which is generated by selenium testcase
     */
    public web_OtherUserProFile(WebDriver driver) {
        super(driver);
    }

    public boolean toggleFollowButton(){
        waitForWebElementToAppear(FollowButton,1);
        FollowButton.click();
        threadSleep(1);
        if(FollowButton.getText()=="Following"){
            //pop p message
            threadSleep(1);
            FollowButton.click();
            threadSleep(1);
            if(FollowButton.getText()=="Follow") {
                FollowButton.click();
                return true;
            }else{
                return false;
            }
        }else {
            return false;
        }
    }
}
